export const recommendations = [
  {
    id: 4,
    name: 'Anjali Mehta',
    title: 'Plumber',
    profile_image_url:
      'https://images.pexels.com/photos/3938023/pexels-photo-3938023.jpeg',
    description:
      'Certified plumber with expertise in bathroom and kitchen fittings.',
    location: 'Delhi, India',
    price: 400,
    experience_years: 5,
    languages_spoken: ['Hindi', 'English'],
    skills: ['Pipe Fixing', 'Tap Installation', 'Leak Repair'],
    certifications: ['City Plumbing License'],
    available_days: ['Tuesday', 'Thursday', 'Saturday'],
    availability_hours: '10 AM - 7 PM',
    verified: true,
    service_area_km: 10,
    rating: 4.3,
    reviews: [
      {user: 'Rajiv T.', comment: 'Fixed the leak in no time!', rating: 4.5},
      {user: 'Preeti S.', comment: 'Affordable and reliable.', rating: 4},
    ],
  },
  {
    id: 5,
    name: 'Vikram Chauhan',
    title: 'Painter',
    profile_image_url:
      'https://images.pexels.com/photos/5691539/pexels-photo-5691539.jpeg',
    description:
      'Professional painter with over 8 years of experience in interior and exterior painting.',
    location: 'Bangalore, Karnataka',
    price: 600,
    experience_years: 8,
    languages_spoken: ['Kannada', 'English'],
    skills: ['Wall Painting', 'Texture Design', 'Waterproofing'],
    certifications: ['Certified Home Decor Specialist'],
    available_days: ['Monday', 'Wednesday', 'Saturday'],
    availability_hours: '8 AM - 5 PM',
    verified: true,
    service_area_km: 20,
    rating: 4.8,
    reviews: [
      {
        user: 'Manju V.',
        comment: 'Transformed my living room beautifully.',
        rating: 5,
      },
      {user: 'Karan M.', comment: 'Neat and quick job.', rating: 4.7},
    ],
  },
  {
    id: 6,
    name: 'Farhan Ali',
    title: 'AC Technician',
    profile_image_url:
      'https://images.pexels.com/photos/3771836/pexels-photo-3771836.jpeg',
    description:
      'Specialist in AC installation and maintenance with 6 years of experience.',
    location: 'Hyderabad, Telangana',
    price: 550,
    experience_years: 6,
    languages_spoken: ['Urdu', 'Hindi', 'English'],
    skills: ['AC Installation', 'Gas Refilling', 'Cooling Issue Fix'],
    certifications: ['HVAC Certified', 'Safety Protocol Certified'],
    available_days: ['Monday', 'Thursday', 'Sunday'],
    availability_hours: '11 AM - 8 PM',
    verified: false,
    service_area_km: 25,
    rating: 4.4,
    reviews: [
      {user: 'Sana Q.', comment: 'Quick diagnosis and repair.', rating: 4.5},
      {user: 'Rohit R.', comment: 'Polite and punctual.', rating: 4.3},
    ],
  },
  {
    id: 7,
    name: 'Priya Nair',
    title: 'Cleaner',
    profile_image_url:
      'https://images.pexels.com/photos/3768913/pexels-photo-3768913.jpeg',
    description: 'Home and office cleaner with attention to detail and safety.',
    location: 'Kochi, Kerala',
    price: 300,
    experience_years: 3,
    languages_spoken: ['Malayalam', 'English'],
    skills: ['Dusting', 'Floor Cleaning', 'Sanitizing'],
    certifications: ['Basic Hygiene Certification'],
    available_days: ['Tuesday', 'Friday', 'Saturday'],
    availability_hours: '9 AM - 2 PM',
    verified: true,
    service_area_km: 12,
    rating: 4.2,
    reviews: [
      {user: 'Neelima J.', comment: 'Very clean and organized.', rating: 4.2},
      {
        user: 'Arun T.',
        comment: 'Great service for a reasonable price.',
        rating: 4.3,
      },
    ],
  },
  {
    id: 8,
    name: 'Suresh Babu',
    title: 'Carpenter',
    profile_image_url:
      'https://images.pexels.com/photos/4475590/pexels-photo-4475590.jpeg',
    description: '10+ years experience in modular furniture and wood repair.',
    location: 'Chennai, Tamil Nadu',
    price: 700,
    experience_years: 10,
    languages_spoken: ['Tamil', 'English'],
    skills: ['Table Repair', 'Wardrobe Setup', 'Door Fixing'],
    certifications: ['Woodcraft Training Certification'],
    available_days: ['Monday', 'Wednesday', 'Thursday'],
    availability_hours: '10 AM - 6 PM',
    verified: true,
    service_area_km: 18,
    rating: 4.7,
    reviews: [
      {
        user: 'Divya S.',
        comment: 'Built a custom shelf exactly as requested.',
        rating: 5,
      },
      {user: 'Gopal K.', comment: 'Clean finish and timely work.', rating: 4.6},
    ],
  },
  {
    id: 9,
    title: 'Labour',
    name: 'General Labour',
    description:
      'Skilled general labourers available for construction, loading, and unloading tasks.',
    price: 15,
    experience_years: 5,
    languages_spoken: ['Hindi', 'English'],
    location: 'Delhi, India',
    verified: true,
    profile_image_url: 'https://example.com/images/labour1.jpg',
    available_days: [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    availability_hours: '8AM - 6PM',
    rating: 4.2,
    skills: ['Loading', 'Unloading', 'Site cleaning'],
    certifications: ['Safety Training'],
    service_area_km: 10,
    reviews: [
      {
        user: 'Rahul Sharma',
        comment: 'Hardworking and punctual.',
        rating: 5,
      },
      {
        user: 'Pooja Singh',
        comment: 'Very efficient!',
        rating: 4,
      },
    ],
  },
  {
    id: 10,
    title: 'Carpenter',
    name: 'Woodwork Specialist',
    description:
      'Expert carpentry services including furniture repair and custom builds.',
    price: 20,
    experience_years: 8,
    languages_spoken: ['Hindi', 'Punjabi'],
    location: 'Ludhiana, Punjab',
    verified: true,
    profile_image_url: 'https://example.com/images/carpenter1.jpg',
    available_days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    availability_hours: '9AM - 5PM',
    rating: 4.6,
    skills: ['Furniture making', 'Door fitting', 'Polishing'],
    certifications: ['Woodwork Diploma'],
    service_area_km: 15,
    reviews: [
      {
        user: 'Amit Patel',
        comment: 'Did a great job with our kitchen cabinets.',
        rating: 5,
      },
    ],
  },
  {
    id: 11,
    title: 'Electrician',
    name: 'Certified Electrician',
    description:
      'Licensed electrician for wiring, installation, and troubleshooting.',
    price: 25,
    experience_years: 10,
    languages_spoken: ['English', 'Hindi'],
    location: 'Mumbai, Maharashtra',
    verified: true,
    profile_image_url: 'https://example.com/images/electrician1.jpg',
    available_days: [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ],
    availability_hours: '10AM - 8PM',
    rating: 4.8,
    skills: ['Wiring', 'Appliance repair', 'Lighting setup'],
    certifications: ['Electrical License Level 2'],
    service_area_km: 20,
    reviews: [
      {
        user: 'Sneha Verma',
        comment: 'Fixed all wiring issues quickly and safely.',
        rating: 5,
      },
    ],
  },
];
